# Generated by Django 2.1.1 on 2018-09-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20180926_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='message',
        ),
        migrations.AddField(
            model_name='post',
            name='message',
            field=models.TextField(default='', max_length=4000),
        ),
    ]
